# Exported from:        http://localhost:5516/
# Release version:      23.1.6
# Date created:         Fri Sep 06 15:11:21 UTC 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: 217694-git
spec:
- name: Deploy
  type: xldeploy.XLDeployServer
  url: http://localhost:4516
  username: admin
  password: !value "xldeploy_XLDeployServer_Deploy_password"
