# Exported from:        http://localhost:5516/
# Release version:      23.1.6
# Date created:         Fri Sep 06 15:11:21 UTC 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: 217694-git
spec:
- template: first
  scheduledStartDate: 2024-09-05T03:30:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: m1
      type: xlrelease.Task
  riskProfile: Default risk profile
- template: second
  scheduledStartDate: 2024-09-05T03:30:00Z
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
