# Exported from:        http://localhost:5516/
# Release version:      23.3.11
# Date created:         Tue Sep 10 13:43:06 UTC 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: xlr23_3
spec:
- template: test123
  scheduledStartDate: 2024-09-10T03:30:00Z
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
