# Exported from:        http://localhost:5516/
# Release version:      24.1.6
# Date created:         Thu Sep 05 07:36:04 GMT 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: "217694"
spec:
- template: second
  scheduledStartDate: 2024-09-05T03:30:00Z
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
